# typical docker-compose file for postgresql
version: '3'

networks:
    net1:

services:
    postgres:
        image: postgres:11-alpine
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
          - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            net1:
                aliases:
                    - postgres
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: root@root.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - 8081:80
        depends_on:
            - postgres
        networks:
            net1:
                aliases:
                    - pgadmin
    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8080:8080
    #   networks:
    #       net1:
    #           aliases:
    #               - pgadmin

    # phppgadmin:
    #     image: dockage/phppgadmin:latest
    #     container_name: phppgadmin
    #     # restart: always
    #     ports:
    #         - "8000:80"
    #     environment:
    #         - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
    #         - PHP_PG_ADMIN_SERVER_HOST=postgres
    #         - PHP_PG_ADMIN_SERVER_PORT=5432
    #         - PHP_PG_ADMIN_SERVER_DEFAULT_DB=postgres
    #         - PHP_PG_ADMIN_SERVER_PG_DUMP_PATH=/usr/bin/pg_dump
    #         - PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH=/usr/bin/pg_dumpall
    #         - PHP_PG_ADMIN_DEFAULT_LANG=auto
    #         - PHP_PG_ADMIN_AUTO_COMPLETE=default on
    #         - PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY=false
    #         - PHP_PG_ADMIN_THEME=default
    #     networks:
    #         net1:
    #             aliases:
    #                 - phppgadmin
