# typical docker-compose file for redis
version: '3'

networks:
    net1:

services:
    redis:
        image: redis:5.0.3-alpine
        container_name: redis
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
        volumes:
            - ./redis-data:/data
        networks:
            net1:
                aliases:
                    - redis
    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: redis-commander
        environment:
            - REDIS_HOSTS=<your label>:redis:6379
            - HTTP_USER=<your user name>
            - HTTP_PASSWORD=<your password>
        ports:
            - 8081:8081
        networks:
            net1:
                aliases:
                    - redis-commander