# typical docker-compose file for spring boot app
version: '3'

networks:
    net1:

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        command: >
          mysqld
          --character-set-server=utf8mb4
          --character_set_filesystem=utf8mb4
          --collation-server=utf8mb4_unicode_ci
          --init-connect='SET NAMES utf8mb4;'
          --skip-character-set-client-handshake
        environment:
            MYSQL_ROOT_PASSWORD: <Your db password>
            MYSQL_DATABASE: <Your db name>
            MYSQL_USER: <optional>
            MYSQL_PASSWORD: <optional>
        volumes:
            - /var/www/<your app name>/data:/var/lib/mysql
        networks:
            net1:
                aliases:
                    - mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
        ports:
            - 8090:80
        depends_on:
            - mysql
        networks:
            net1:
                aliases:
                    - phpmyadmin
    app:
        image: <spring boot image>
        container_name: app
        environment:
            TZ: <Your timezone: e.g. Asia/Shanghai>
            SPRING_PROFILES_ACTIVE: prod
        depends_on:
            - mysql
        ports:
            - 8080:8080
        volumes:
            - /var/www/<your app name>/log:/app/log
            - /var/www/<your app name>/config:/app/config
        networks:
            net1:
                aliases:
                    - app
    app-client:
        image: <front end app image>
        container_name: app-client
        environment:
            APP_API_GATEWAY: http://app:8080/api/v1
        depends_on:
            - app
        ports:
            - 80:80
        networks:
            net1:
                aliases:
                    - app-client
